export const TOKENS = {
  colors: {
    light: {
      bg: '#FBF6EE',
      surface: '#FFFFFF',
      surface2: '#F5EDE0',
      ink: '#1F2421',
      muted: '#6B6F68',
      brand: '#1F5B45',
      brandHover: '#184736',
      peach: '#FFD9C2',
      orange: '#E8742C',
      amber: '#F2B33D',
      lavender: '#DCD1F7',
      mint: '#D5EEE1',
    },
    dark: {
      bg: '#14171A',
      surface: '#1D2125',
      surface2: '#252A2F',
      ink: '#F2EEE6',
      muted: '#A5A9A2',
      brand: '#5FBF95',
      brandHover: '#74CCA5',
      peach: '#D9896A',
      orange: '#F08B4B',
      amber: '#F5BE59',
      lavender: '#8D7AB5',
      mint: '#4A7F66',
    },
    nutrient: {
      protein: '#2E9E5B',
      carbs: '#F2B33D',
      fat: '#7C8CF0',
      fiber: '#2F9E8F',
      iron: '#E2582E',
      calcium: '#2BB3CE',
      b12: '#7B5CD6',
      folate: '#D9649B',
      sodium: '#8A8F98',
      vitaminD: '#F0A63A',
      hydration: '#2BB3CE',
      energy: '#F2B33D',
    },
  },
  confidenceBands: {
    high: { min: 0.80, label: 'High confidence', color: '#2E9E5B' },
    medium: { min: 0.50, max: 0.79, label: 'Moderate confidence', color: '#F2B33D' },
    low: { max: 0.49, label: 'Uncertain estimate', color: '#E2582E' },
    warningThreshold: 0.60,
  },
  durations: {
    fast: 120,
    base: 220,
    slow: 420,
    splashTotal: 5000,
  },
  storageKeys: {
    auth: 'nutrisense:v1:auth',
    profile: 'nutrisense:v1:profile',
    meals: 'nutrisense:v1:meals',
    settings: 'nutrisense:v1:settings',
    streak: 'nutrisense:v1:streak',
    achievements: 'nutrisense:v1:achievements',
    splashSeen: 'nutrisense:v1:splash_seen',
  },
  motes: {
    protein: { name: 'Protein', color: '#2E9E5B', shape: 'hex-chain' },
    iron: { name: 'Iron', color: '#E2582E', shape: 'faceted-pebble' },
    calcium: { name: 'Calcium', color: '#2BB3CE', shape: 'crystal-shard' },
    b12: { name: 'Vitamin B12', color: '#7B5CD6', shape: 'halo-orb' },
    hydration: { name: 'Hydration', color: '#2BB3CE', shape: 'water-droplet' },
    energy: { name: 'Energy', color: '#F2B33D', shape: 'pulsing-ember' },
    fiber: { name: 'Fiber', color: '#2F9E8F', shape: 'leaf-spiral' },
  },
} as const;

export type MoteType = keyof typeof TOKENS.motes;
export type MoteMood = 'idle' | 'curious' | 'happy' | 'celebrating' | 'resting';
